application: worldhello
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: main.php

- url: /stylesheets
  static_dir: stylesheets

- url: /page.php
  script: page.php


# application: myapp
# version: 1
# runtime: php
# api_version: 1

# handlers:
# # Serve images as static resources.
# - url: /(.+\.(gif|png|jpg))$
#   static_files: \1
#   upload: .+\.(gif|png|jpg)$
#   application_readable: true

# # Serve php scripts.
# - url: /(.+\.php)$
#   script: \1